#!/usr/bin/env node
// GitHub labels and .github/labeler.yml for the factory (SPEC 10.2, 10.3; MASTER-PLAN D-20). Owner: F.
//
//   node tools/labels.mjs --list                 print every label (static + site:<slug> + pack:<type>) as JSON
//   node tools/labels.mjs --labeler              print the generated .github/labeler.yml
//   node tools/labels.mjs --labeler --write      write .github/labeler.yml
//   node tools/labels.mjs --check                exit 1 when tools/labels.json is malformed or
//                                                .github/labeler.yml is not the generated text
//   node tools/labels.mjs --seed [--repo owner/name] [--dry-run]
//                                                create missing labels and update changed colours or
//                                                descriptions through the GitHub REST API
//                                                (token: GITHUB_TOKEN or GH_TOKEN; repo: --repo,
//                                                GITHUB_REPOSITORY or the origin remote). Never deletes.
//
// Sources: tools/labels.json (static labels and labeler rules), sites/<slug>/ (not _-prefixed:
// fixtures are not sites) and types/<type>/. Exit codes: 0 ok, 1 check failed or API error, 2 usage.

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG = path.join(REPO, 'tools', 'labels.json');
const LABELER = path.join(REPO, '.github', 'labeler.yml');

function dirs(rel) {
  const abs = path.join(REPO, rel);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map((d) => d.name)
    .sort();
}

export function loadConfig() {
  return JSON.parse(fs.readFileSync(CONFIG, 'utf8'));
}

export function allLabels(cfg = loadConfig()) {
  const out = [...cfg.labels];
  const g = cfg.generated;
  for (const slug of dirs('sites')) out.push({ name: `${g.site.prefix}${slug}`, color: g.site.color, description: g.site.description.replace('{slug}', slug) });
  for (const type of dirs('types')) out.push({ name: `${g.pack.prefix}${type}`, color: g.pack.color, description: g.pack.description.replace('{type}', type) });
  return out;
}

export function validate(cfg = loadConfig()) {
  const errors = [];
  const seen = new Set();
  for (const l of allLabels(cfg)) {
    if (!l.name || l.name.length > 50) errors.push(`label name missing or longer than 50: ${JSON.stringify(l.name)}`);
    if (seen.has(l.name)) errors.push(`duplicate label ${l.name}`);
    seen.add(l.name);
    if (!/^[0-9a-f]{6}$/.test(l.color || '')) errors.push(`${l.name}: color must be 6 lowercase hex digits`);
    if ((l.description || '').length > 100) errors.push(`${l.name}: description longer than 100 characters`);
  }
  for (const [name, globs] of Object.entries(cfg.labeler || {})) {
    if (!seen.has(name)) errors.push(`labeler rule for unknown label ${name}`);
    if (!Array.isArray(globs) || !globs.length) errors.push(`labeler rule ${name} needs a non-empty glob list`);
  }
  return errors;
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

export function labelerYaml(cfg = loadConfig()) {
  const rules = [];
  for (const slug of dirs('sites')) rules.push([`${cfg.generated.site.prefix}${slug}`, [`sites/${slug}/**`, `orders/${slug}/**`]]);
  for (const type of dirs('types')) rules.push([`${cfg.generated.pack.prefix}${type}`, [`types/${type}/**`]]);
  for (const [name, globs] of Object.entries(cfg.labeler || {})) rules.push([name, globs]);
  const lines = [
    '# Generated by `node tools/labels.mjs --labeler --write` from tools/labels.json, sites/ and types/.',
    '# Do not edit by hand: `node tools/labels.mjs --check` (engine-ci) fails when this file is stale.',
    '# Format: actions/labeler v5.',
  ];
  for (const [name, globs] of rules) {
    lines.push(`${q(name)}:`, '  - changed-files:', '      - any-glob-to-any-file:');
    for (const g of globs) lines.push(`          - ${q(g)}`);
  }
  return lines.join('\n') + '\n';
}

function repoSlug(argv) {
  const i = argv.indexOf('--repo');
  if (i >= 0 && argv[i + 1]) return argv[i + 1];
  if (process.env.GITHUB_REPOSITORY) return process.env.GITHUB_REPOSITORY;
  try {
    const url = execFileSync('git', ['-C', REPO, 'remote', 'get-url', 'origin'], { encoding: 'utf8' }).trim();
    const m = url.match(/github\.com[:/]+([^/]+\/[^/.]+?)(?:\.git)?$/) || url.match(/\/git\/([^/]+\/[^/.]+?)(?:\.git)?$/);
    if (m) return m[1];
  } catch { /* no git */ }
  return null;
}

async function api(method, url, token, body) {
  const res = await fetch(`https://api.github.com${url}`, {
    method,
    headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}`, 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'site-factory-labels' },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(`${method} ${url}: HTTP ${res.status} ${await res.text()}`);
  return res.status === 204 ? null : res.json();
}

async function seed(argv) {
  const dry = argv.includes('--dry-run');
  const repo = repoSlug(argv);
  if (!repo) { console.error('labels: cannot tell the repository; pass --repo owner/name'); return 2; }
  const wanted = allLabels();
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const offline = () => {
    for (const l of wanted) console.log(`would ensure ${l.name} (#${l.color}) on ${repo}`);
    return 0;
  };
  if (!token) {
    if (!dry) { console.error('labels: set GITHUB_TOKEN or GH_TOKEN, or use --dry-run'); return 2; }
    return offline();
  }
  const existing = new Map();
  try {
    for (let page = 1; ; page++) {
      const batch = await api('GET', `/repos/${repo}/labels?per_page=100&page=${page}`, token);
      for (const l of batch) existing.set(l.name, l);
      if (batch.length < 100) break;
    }
  } catch (err) {
    if (!dry) throw err;
    console.error(`labels: cannot read the current labels (${err.message.split('\n')[0]}); listing offline`);
    return offline();
  }
  let created = 0, updated = 0;
  for (const l of wanted) {
    const have = existing.get(l.name);
    if (!have) {
      if (dry) console.log(`would create ${l.name}`);
      else await api('POST', `/repos/${repo}/labels`, token, l);
      created++;
    } else if (have.color.toLowerCase() !== l.color || (have.description || '') !== (l.description || '')) {
      if (dry) console.log(`would update ${l.name}`);
      else await api('PATCH', `/repos/${repo}/labels/${encodeURIComponent(l.name)}`, token, { color: l.color, description: l.description });
      updated++;
    }
  }
  console.log(JSON.stringify({ repo, dryRun: dry, created, updated, unchanged: wanted.length - created - updated }));
  return 0;
}

async function main(argv) {
  if (argv.includes('--list')) { console.log(JSON.stringify(allLabels(), null, 2)); return 0; }
  if (argv.includes('--labeler')) {
    const text = labelerYaml();
    if (argv.includes('--write')) { fs.writeFileSync(LABELER, text); console.log(`wrote ${path.relative(REPO, LABELER)}`); }
    else process.stdout.write(text);
    return 0;
  }
  if (argv.includes('--check')) {
    const errors = validate();
    const have = fs.existsSync(LABELER) ? fs.readFileSync(LABELER, 'utf8') : '';
    if (have !== labelerYaml()) errors.push('.github/labeler.yml is stale: run node tools/labels.mjs --labeler --write');
    for (const e of errors) console.error(`labels: ${e}`);
    if (!errors.length) console.log(`labels: ok (${allLabels().length} labels)`);
    return errors.length ? 1 : 0;
  }
  if (argv.includes('--seed')) return seed(argv);
  console.error('usage: node tools/labels.mjs --list | --labeler [--write] | --check | --seed [--repo owner/name] [--dry-run]');
  return 2;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).then((code) => process.exit(code), (err) => { console.error(`labels: ${err.message}`); process.exit(1); });
}
