#!/usr/bin/env node
// Static site build. No dependencies: Node 20 or later.
//
//   node build.mjs            build into dist/
//   node build.mjs --strict   also fail on placeholder operator details
//
// Reads site.config.json, renders every page to plain HTML, copies
// src/public, and writes sitemap, robots, manifest, service worker and
// hosting headers. Then it lints the output against the site's rules.

import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

import { makeContext } from './src/lib/context.mjs';
import { layout, setAssetVersion, csp } from './src/lib/layout.mjs';
import home from './src/pages/home.mjs';
import gamesIndex from './src/pages/games-index.mjs';
import sevenSystems from './src/pages/seven-systems.mjs';
import lapidaryWheel from './src/pages/lapidary-wheel.mjs';
import brilliant21 from './src/pages/brilliant-twenty-one.mjs';
import about from './src/pages/about.mjs';
import responsibleGaming from './src/pages/responsible-gaming.mjs';
import terms from './src/pages/terms.mjs';
import privacy from './src/pages/privacy.mjs';
import cookies from './src/pages/cookies.mjs';
import contact from './src/pages/contact.mjs';
import { notFound, offline } from './src/pages/misc.mjs';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(ROOT, process.env.OUT_DIR || 'dist');
const PUBLIC = path.join(ROOT, 'src/public');
const strict = process.argv.includes('--strict');

const cfg = JSON.parse(await fs.readFile(path.join(ROOT, process.env.SITE_CONFIG || 'site.config.json'), 'utf8'));
const ctx = makeContext(cfg);

// ---------- helpers ----------
async function walk(dir) {
  const out = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}
const write = async (rel, data) => {
  const p = path.join(OUT, rel);
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, data);
};
const gz = (buf) => zlib.gzipSync(buf, { level: 9 }).length;
const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

// ---------- 1. copy public files ----------
await fs.rm(OUT, { recursive: true, force: true });
await fs.cp(PUBLIC, OUT, { recursive: true });

// Asset version: a hash of every CSS and JS file, for cache busting.
const assetFiles = (await walk(path.join(OUT, 'assets'))).filter((f) => /\.(css|js)$/.test(f)).sort();
const h = crypto.createHash('sha256');
for (const f of assetFiles) h.update(await fs.readFile(f));
const version = h.digest('hex').slice(0, 10);
setAssetVersion(version);

// Client config, generated from site.config.json so the browser code has
// the same brand, currency and analytics settings as the pages.
await write(
  'assets/js/config.js',
  `// Generated by build.mjs from site.config.json. Don't edit by hand.\nexport default ${JSON.stringify(
    {
      brand: cfg.brand,
      currency: cfg.currency,
      analytics: cfg.analytics,
      contactEndpoint: cfg.contactEndpoint,
      version,
    },
    null,
    2,
  )};\n`,
);

// ---------- 2. pages ----------
const pages = [
  home(ctx),
  gamesIndex(ctx),
  sevenSystems(ctx),
  lapidaryWheel(ctx),
  brilliant21(ctx),
  about(ctx),
  responsibleGaming(ctx),
  terms(ctx),
  privacy(ctx),
  cookies(ctx),
  contact(ctx),
  notFound(ctx),
  offline(ctx),
];

for (const page of pages) {
  const file = page.file || path.join(page.path, 'index.html');
  page.outFile = file;
  page.html = layout(ctx, page)
    // Wide tables scroll sideways on phones; make each scroll box reachable by keyboard and named after its caption.
    .replace(/<div class="table-wrap">(\s*<table[^>]*>\s*<caption[^>]*>([\s\S]*?)<\/caption>)/g, (m, rest, cap) =>
      `<div class="table-wrap" tabindex="0" role="region" aria-label="${cap.replace(/<[^>]+>/g, '').replace(/"/g, '&quot;').trim()}">${rest}`);
  await write(file, page.html);
}

// ---------- 3. site files ----------
const indexed = pages.filter((p) => p.sitemap !== false);
await write(
  'sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexed
    .map((p) => `  <url><loc>${ctx.origin}${p.path}</loc><lastmod>${cfg.lastUpdated}</lastmod></url>`)
    .join('\n')}\n</urlset>\n`,
);
await write('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${ctx.origin}/sitemap.xml\n`);
await write('CNAME', `${cfg.domain}\n`);

await write(
  'manifest.webmanifest',
  JSON.stringify(
    {
      name: cfg.brand,
      short_name: cfg.shortName,
      description: `Free-to-play games with virtual ${cfg.currency.plural}. No real money, no prizes. Adults 18+.`,
      id: '/',
      start_url: '/?source=pwa',
      scope: '/',
      display: 'standalone',
      orientation: 'any',
      lang: 'en-GB',
      dir: 'ltr',
      background_color: cfg.themeColor.dark,
      theme_color: cfg.themeColor.dark,
      categories: ['games', 'entertainment'],
      icons: [
        { src: '/assets/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: '/assets/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: '/assets/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
      shortcuts: ctx.games.map((g) => ({ name: g.name, url: g.path, icons: [{ src: '/assets/icons/icon-192.png', sizes: '192x192' }] })),
    },
    null,
    2,
  ),
);

// Cloudflare Pages headers. GitHub Pages ignores this file; the pages
// carry the same Content-Security-Policy in a meta tag.
await write(
  '_headers',
  `/*
  Content-Security-Policy: ${csp(ctx)}; frame-ancestors 'none'; upgrade-insecure-requests
  Strict-Transport-Security: max-age=63072000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()
  Cross-Origin-Opener-Policy: same-origin

/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/assets/img/*
  Cache-Control: public, max-age=2592000

/assets/*
  Cache-Control: public, max-age=3600, stale-while-revalidate=604800

/sw.js
  Cache-Control: no-cache
`,
);

// Service worker: precache everything the site needs to run offline.
const allFiles = (await walk(OUT)).map((f) => '/' + path.relative(OUT, f).split(path.sep).join('/'));
const precache = allFiles
  .filter((f) => !/^\/(_headers|CNAME|robots\.txt|sitemap\.xml|sw\.js)$/.test(f))
  .filter((f) => !/\/og-[^/]+\.png$/.test(f) && !/-960\.(avif|webp)$/.test(f))
  .map((f) => f.replace(/index\.html$/, ''))
  .sort();
const swTemplate = await fs.readFile(path.join(ROOT, 'src/sw.template.js'), 'utf8');
const swHash = crypto.createHash('sha256').update(version + precache.join()).digest('hex').slice(0, 10);
await write('sw.js', swTemplate.replace('__VERSION__', swHash).replace('__PRECACHE__', JSON.stringify(precache, null, 2)));

// ---------- 4. lint ----------
const problems = [];
const warnings = [];
const visibleText = (s) =>
  s
    .replace(/<script[\s\S]*?<\/script>/g, ' ')
    .replace(/<style[\s\S]*?<\/style>/g, ' ')
    .replace(/<code>[\s\S]*?<\/code>/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&[a-z#0-9]+;/gi, ' ');

const FORBIDDEN = [/\bdeposit/i, /\bwithdraw/i, /cash[\s-]?out/i, /bonus code/i, /real[\s-]money wins?/i, /win big/i, /jackpot/i, /\bhurry\b/i, /don[’']t miss out/i];
const AMERICAN = [/\bcolor\b/i, /\bfavor/i, /\bcenter\b/i, /\bbehavior/i, /\bgray\b/i, /\borganization\b/i, /\bcatalog\b/i, /\blicense\b/i, /\banalyz/i, /\bcustomiz/i, /\boptimiz/i, /\bjewelry\b/i];

const files = await walk(OUT);
for (const f of files) {
  if (!/\.(html|js|json|webmanifest|css|txt|xml)$/.test(f)) continue;
  const rel = path.relative(OUT, f);
  const src = await fs.readFile(f, 'utf8');
  const text = /\.html$/.test(f) ? visibleText(src) : src;
  for (const re of FORBIDDEN) if (re.test(text)) problems.push(`${rel}: forbidden wording ${re}`);
  if (/\.html$/.test(f)) for (const re of AMERICAN) if (re.test(text)) problems.push(`${rel}: American spelling ${re}`);
}

for (const page of pages) {
  const s = page.html;
  const rel = page.outFile;
  const h1s = (s.match(/<h1[\s>]/g) || []).length;
  if (h1s !== 1) problems.push(`${rel}: ${h1s} <h1> elements`);
  if (page.title.length > 60) problems.push(`${rel}: title is ${page.title.length} characters`);
  if (page.description.length > 155) problems.push(`${rel}: description is ${page.description.length} characters`);
  if (!s.includes('lang="en-GB"')) problems.push(`${rel}: missing lang="en-GB"`);
  if (page.canonical !== false && !s.includes('rel="canonical"')) problems.push(`${rel}: no canonical`);
  if (!s.includes(ctx.disclaimer)) problems.push(`${rel}: disclaimer missing`);
  for (const m of s.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    let data;
    try { data = JSON.parse(m[1]); } catch (e) { problems.push(`${rel}: invalid JSON-LD (${e.message})`); continue; }
    for (const node of data['@graph'] || [data]) {
      if (node['@type'] === 'VideoGame') {
        const ok = node.isAccessibleForFree === true && node.offers?.price === 0 && node.gamePlatform === 'Web browser' && node.name && node.url;
        if (!ok) problems.push(`${rel}: VideoGame JSON-LD is missing isAccessibleForFree, offers.price 0 or gamePlatform`);
      }
      if (node['@type'] === 'BreadcrumbList' && !node.itemListElement?.every((i, k) => i.position === k + 1 && i.item?.startsWith(ctx.origin))) {
        problems.push(`${rel}: BreadcrumbList positions or URLs are wrong`);
      }
    }
  }
  // internal links and assets must exist
  for (const m of s.matchAll(/(?:href|src|srcset)="(\/[^"#?]*)/g)) {
    for (const part of m[1].split(/,\s*/)) {
      const url = part.split(' ')[0];
      if (!url.startsWith('/')) continue;
      const target = url.endsWith('/') ? path.join(OUT, url, 'index.html') : path.join(OUT, url);
      try { await fs.access(target); } catch {
        if (!/\/assets\/(img|icons)\/|favicon\.ico/.test(url)) problems.push(`${rel}: broken link ${url}`);
        else warnings.push(`${rel}: missing image ${url} (run npm run images)`);
      }
    }
  }
}

for (const [k, v] of Object.entries(cfg.operator)) {
  if (/\[.*\]/.test(v)) (strict ? problems : warnings).push(`site.config.json: operator.${k} is still a placeholder: "${v}"`);
}

// First-view budget on the home page: HTML + CSS + every JS module it loads.
async function moduleGraph(entries) {
  const seen = new Set();
  const queue = [...entries];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    seen.add(rel);
    let src;
    try { src = await fs.readFile(path.join(OUT, rel), 'utf8'); } catch { continue; }
    for (const m of src.matchAll(/(?:import|export)\s[^'"]*?from\s*['"](\.[^'"]+)['"]|import\s*['"](\.[^'"]+)['"]/g)) {
      queue.push(path.posix.join(path.posix.dirname(rel), m[1] || m[2]));
    }
  }
  return [...seen];
}
const homePage = pages[0];
const firstView = await moduleGraph(['assets/js/app.js', ...[...(homePage.modules || []), ...(homePage.budgetModules || [])].map((m) => m.slice(1))]);
let budget = gz(Buffer.from(homePage.html)) + gz(await fs.readFile(path.join(OUT, 'assets/css/site.css')));
for (const m of firstView) {
  try { budget += gz(await fs.readFile(path.join(OUT, m))); } catch {}
}
if (budget > 150 * 1024) problems.push(`home first view is ${kb(budget)} gzip, over the 150 KB budget`);

// ---------- 5. report ----------
console.log(`Built ${pages.length} pages into ${path.relative(process.cwd(), OUT) || '.'}/ (assets v${version}, sw ${swHash})`);
console.log(`Home first view (HTML + CSS + ${firstView.length} JS modules): ${kb(budget)} gzip of 150 KB budget`);
for (const w of new Set(warnings.map((w) => w.replace(/^[^:]+: (missing image)/, '$1')))) console.warn(`warning: ${w}`);
if (problems.length) {
  for (const p of problems) console.error(`error: ${p}`);
  process.exit(1);
}
console.log('Lint: no problems found.');
